name: package_info_linux
version: 0.0.0-dev
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  ffigen: 
    git:
      url: https://github.com/dart-lang/ffigen.git
  pedantic: ^1.9.0
  test: ^1.15.3
