name: flutter_playground
description: A Flutter playground project.
publish_to: 'none'
version: 0.0.0-dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  battery_linux:
    path: ../battery_linux
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
